
# **LIBRERÍA NUMPY**

Sinonimo de *Numerical Python*, `numpy` es una librería que proporciona herramientas para trabajar con alto rendimiento sobre arreglos multidimensionales.


## Características:
Dentro de las principales características de `numpy` se encuentran:
- Ofrece un poderoso objeto para manipular arreglos multidimensionales: `ndarray`.
- Posee herramientas para realizar operaciones matemáticas y lógicas sobre arreglos, operaciones relacionadas con algebra lineal, transformadas de Fourier, entre otras.

Para importar los módulos de la librería `numpy`, por convención se utiliza:

In [1]:
# Importamos Numpy con el alias np
import numpy as np

## Arrays


Las funcionalidades de `numpy` se basan en en el objeto `ndarray`.

Un `ndarray`, también conocido por el alias de `array`, es un arreglo N-dimensional con elementos del mismo tipo e indexado por una tupla de enteros positivos.


```python
a = numpy.array(data, dtype = None, ndmin = 0, ...)
```
- data: datos de mismo tipo en forma de matriz o una secuencia anidada.
- dtype (opcional): tipos de datos deseados en el arreglo.
- ndmin: especifica el número mínimo de dimensiones del arreglo resultante.

Crea una lista y conviértela en una matriz numpy:

In [2]:
a = np.array([[0,1,2,3],[4,5,6,7],[1,2,3,4]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 2, 3, 4]])

O simplemente pasa una lista directamente:

In [3]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Pasa una lista de listas para crear una matriz multidimensional:

In [4]:
m = np.array([[0,1,2,3],[4,5,6,7],[1,2,3,4]])
m

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 2, 3, 4]])

Dentro de los principales atributos del objeto `ndarray`, se encuentran:
- `ndarray.shape`: tupla con las dimensiones del arreglo.
- `ndarray.ndim`: numero de dimensiones del arreglo.
- `ndarray.size`: número de elementos del arreglo.
- `ndarray.dtype`: tipo de dato de los elementos del arreglo.

In [5]:
m.shape

(3, 4)

In [6]:
m.ndim

2

In [7]:
m.size

12

In [8]:
m.dtype

dtype('int64')

Numpy cuenta con funciones especiales para crear arreglos con valores definidos por defecto, por ejemplo:
- **zeros**: crea arreglo solamente con 0's.
- **ones**: crea arreglo solamente con 1's.
- **eye**: crea una matriz identidad de tamaño n.
- **full**: crea un arreglo con un valor constante especificado.

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<br>`reshape` devuelve una matriz con los mismos datos en una nueva forma:

In [13]:
n1 = np.ones((6, 3))
n1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
n2 = n1.reshape(2, 9) # reshape array to be 2x9
n2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
n3 = n1.reshape(1, 18) # reshape array to be 1x18
n3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

<br>`arange` devuelve valores espaciados uniformemente dentro de un intervalo dado.

In [22]:
n4 = np.arange(0, 30, 2) # inicia en 0, aumenta de 2 en 2 y se detiene en una valor anterior a 30
n4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>`linspace` devuelve números espaciados uniformemente en un intervalo especificado:

In [23]:
n5 = np.linspace(0, 4, 9) # Devuelve 9 valores espaciados uniformemente de 0 a 4
n5

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

<br> `resize` cambia la forma y el tamaño de la matriz de forma definitiva:

In [24]:
n5.resize(3, 3)
n5

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

<br>**diag** extrae una diagonal o construye una matriz diagonal:

In [25]:
np.diag([4,5,6,7])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

<br>Crea una matriz usando la lista de repetición (o ver `np.tile`):

In [26]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [37]:
np.tile(np.arange(1,4),(1,3)) # (1,3): 1 es el número de filas y 3 es el número de repeticiones.

array([[1, 2, 3, 1, 2, 3, 1, 2, 3]])

<br>Repite elementos de un array usando `repeat`.

In [38]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Vector aleatorio

In [39]:
np.random.seed(123)  #si defino la semilla, se reproducen los mismos números aleatorios
w = np.random.rand(10) #vector aleatorio de elementos uniformes entre 0 y 1
print(w)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]


In [40]:
x = np.random.randn(10) #vector aleatorio de elementos normales estandar
print(x)

[ 1.26593626 -0.8667404  -0.67888615 -0.09470897  1.49138963 -0.638902
 -0.44398196 -0.43435128  2.20593008  2.18678609]


In [41]:
y = np.random.randint(0,10,10) #vector aleatorio de elementos enteros
print(y)

[8 0 7 9 3 4 6 1 5 6]


## Matrices

In [42]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11] , [3,5,6,9]])
print(np.shape(a))
print(a)

(4, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 3  5  6  9]]


In [43]:
#Creación de una matriz diagonal

#Primero un rango lineal
a = np.arange(5)
print(a)

#Y ahora lo convertimos en diagonal
diagonal = np.diag(a)
print(diagonal)

[0 1 2 3 4]
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


In [44]:
#Matriz a base de "tiles" (baldosas)
ar = np.array([[6,7],[8,9]])
print(ar)
tiles = np.tile(ar,(2,3))
print(tiles)

[[6 7]
 [8 9]]
[[6 7 6 7 6 7]
 [8 9 8 9 8 9]
 [6 7 6 7 6 7]
 [8 9 8 9 8 9]]


In [45]:
#Cambio de forma de un vector

#Creamos un vector lineal y lo reorganizamos como matriz 3x3
x = np.arange(9)
print(x)
x = x.reshape(3,3)
print(x)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Trabajo con matrices

In [46]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

<br> Utiliza `vstack` para apilar las matrices o arrays en secuencia verticalmente (en sentido de fila):

In [47]:
np.vstack((p, 2*p))

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

<br>Usa `hstack` para apilar las matrices en secuencia horizontalmente (en sentido de columna):

In [48]:
np.hstack((p, 2*p))

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br>Usa `column_stack` para concatenar por matrices horizontalmente (permite concatenar una matriz con un array unidimensional):

In [49]:
np.column_stack((p,[3,5]))

array([[1, 1, 1, 3],
       [1, 1, 1, 5]])

### Operaciones con arrays

Usa `+`, `-`,` * `,` / `y` ** `para realizar sumas, restas, multiplicaciones, divisiones y potencias por elementos:

In [56]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [51]:
print(x + 3) # adición por un escalar
print(x - 3) # resta por un escalar
print(x * 3) # multiplicación por un escalar
print(x / 3) # división por un escalar

[4 5 6]
[-2 -1  0]
[3 6 9]
[0.33333333 0.66666667 1.        ]


In [52]:
print(x + y) # adición por elementos     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # resta por elementos      [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [53]:
print(x * y) # multiplicación por elementos  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # división por elementos        [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [54]:
print(x**2) # potenciación por elementos  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [57]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [58]:
np.dot(x,y)

32

Por otro lado, hay funciones universales que realizan operaciones con 2 arrays y regresan un array como salida.

In [59]:
np.add(x,y)

array([5, 7, 9])

In [60]:
np.multiply(x,y)

array([ 4, 10, 18])

In [61]:
np.power(x,y)

array([  1,  32, 729])

<br>
Veamos las matrices de transposición. La transposición permuta las dimensiones de la matriz.

In [62]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>La forma de la matriz `z` es` (2,3) `antes de la transposición:

In [63]:
z.shape

(2, 3)

<br>Usa `.T` para transponer una matriz:

In [64]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>El número de filas se ha intercambiado con el número de columnas.

In [65]:
z.T.shape

(3, 2)

Probando la multiplicación dot en matrices (producto matricial)

In [66]:
np.dot(z,z.T)

array([[  77,  405],
       [ 405, 2177]])

In [67]:
np.dot(z.T,z)

array([[ 272,  420,  600],
       [ 420,  650,  930],
       [ 600,  930, 1332]])

#### Determinante e inversa de una matriz

In [68]:
w = np.random.randint(0, 50, (4,4))
w

array([[30, 27, 34, 33],
       [12, 40,  3, 42],
       [ 5,  0, 11, 34],
       [10, 22, 13, 18]])

In [69]:
#Determinante: sobre matrices cuadradas
np.linalg.det(w)

-203125.99999999988

In [70]:
#Inversa: sobre matrices cuadradas con determinante diferente de cero
np.linalg.inv(w)

array([[ 0.08703957,  0.05345451, -0.04250564, -0.2040113 ],
       [-0.02002698,  0.00150153, -0.01804791,  0.06730305],
       [-0.02778571, -0.05937202,  0.02510757,  0.14204976],
       [-0.00381044,  0.01134764,  0.02753956, -0.01595561]])

## Funciones sobre arrays

*Numpy* tiene muchas funciones matemáticas integradas que se pueden realizar sobre arrays.

In [71]:
a = np.array([12, 13, 9, 3, 5])
a

array([12, 13,  9,  3,  5])

In [72]:
a.sum()  #suma

42

In [73]:
# alternativamente
np.sum(a)

42

In [74]:
a.prod()  #productoria

21060

In [75]:
a.max()  #maximo

13

In [76]:
a.min()  #mínimo

3

In [77]:
a.mean()  #promedio

8.4

In [78]:
np.median(a)  #mediana

9.0

In [79]:
a.std()   #desviación estándar

3.878143885933063

<br>`argmax` y` argmin` devuelven el índice del valor máximo y mínimo en la matriz:

In [80]:
a.argmax()

1

In [81]:
a.argmin()

3

Otras funciones:

In [82]:
np.exp(a)

array([1.62754791e+05, 4.42413392e+05, 8.10308393e+03, 2.00855369e+01,
       1.48413159e+02])

In [83]:
np.log(a)

array([2.48490665, 2.56494936, 2.19722458, 1.09861229, 1.60943791])

In [84]:
np.sqrt(a)

array([3.46410162, 3.60555128, 3.        , 1.73205081, 2.23606798])

## Indexar/Seleccionar elementos

In [85]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

Usa la notación de corchetes para obtener el valor de un índice específico. Recuerda que la indexación comienza en 0:

In [86]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>Usa `:` para indicar un rango. `array[start:stop]`


Si se deja vacío `start` o `stop`, el inicio/final de la matriz será predeterminado:

In [87]:
s[1:5]

array([ 1,  4,  9, 16])

<br>
Usa negativos para contar desde el final:

In [88]:
s[-4:]

array([ 81, 100, 121, 144])

<br>Se puede usar un segundo símbolo `:` para indicar la magnitud del paso en el que se van a tomar los elmentos: `array[start:stop:stepsize]`

Aquí estamos comenzando en el quinto elemento desde el final, y contando en 2 hacia atrás hasta llegar al comienzo de la matriz:

In [90]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [91]:
s[-5::2]

array([ 64, 100, 144])

<br> **Para matrices:** Usa la notación de paréntesis para dividir: `matriz [fila, columna]`

In [92]:
r = np.random.randint(0, 50, (10,10))
r

array([[36, 15, 43, 27, 44, 30,  6, 45, 26, 16],
       [ 6, 14, 39, 11,  7,  1, 43, 37, 25, 20],
       [49, 12, 18, 17,  1, 44, 41, 48, 27, 49],
       [22,  3,  3, 11, 21, 25, 39, 41, 34,  3],
       [11,  3, 30,  6,  9, 23, 14, 38, 19,  6],
       [12, 27, 38, 17, 46, 10, 35, 35,  1, 47],
       [45, 16,  5, 40, 45, 22, 46, 15, 40, 25],
       [45, 49,  0, 35, 29,  1, 19,  4, 30,  7],
       [29, 38,  1, 12,  3, 44,  7, 38, 24,  6],
       [13, 28, 44, 20, 36, 48, 32, 40, 24, 45]])

In [93]:
r[2, 2]

18

<br>Y usa `:` para seleccionar un rango de filas o columnas. ¡Ten en cuenta que el índice 6 no existe!

In [94]:
r[3, 3:6]

array([11, 21, 25])

In [95]:
r[0:2,0:3]

array([[36, 15, 43],
       [ 6, 14, 39]])

In [96]:
r[1:2, 2:]

array([[39, 11,  7,  1, 43, 37, 25, 20]])

<br>Aquí estamos seleccionando todas las filas hasta (y sin incluir) la fila 2, y todas las columnas hasta (y sin incluir) la última columna:

In [97]:
r[:2, :-1]

array([[36, 15, 43, 27, 44, 30,  6, 45, 26],
       [ 6, 14, 39, 11,  7,  1, 43, 37, 25]])

In [98]:
r[0:2, 0:-1]

array([[36, 15, 43, 27, 44, 30,  6, 45, 26],
       [ 6, 14, 39, 11,  7,  1, 43, 37, 25]])



Esta es una porción de la última fila, y solo los elementos pares:

In [99]:
r[-1, ::2]

array([13, 44, 36, 32, 24])

<br>También podemos realizar indexación condicional. Aquí estamos seleccionando valores de la matriz que son mayores que 30:

In [100]:
r[r > 28]

array([36, 43, 44, 30, 45, 39, 43, 37, 49, 44, 41, 48, 49, 39, 41, 34, 30,
       38, 38, 46, 35, 35, 47, 45, 40, 45, 46, 40, 45, 49, 35, 29, 30, 29,
       38, 44, 38, 44, 36, 48, 32, 40, 45])

<br>Aquí estamos asignando el valor 30 a todos los valores de la matriz que son mayores que 30.

In [101]:
r[r > 30] = 30
r

array([[30, 15, 30, 27, 30, 30,  6, 30, 26, 16],
       [ 6, 14, 30, 11,  7,  1, 30, 30, 25, 20],
       [30, 12, 18, 17,  1, 30, 30, 30, 27, 30],
       [22,  3,  3, 11, 21, 25, 30, 30, 30,  3],
       [11,  3, 30,  6,  9, 23, 14, 30, 19,  6],
       [12, 27, 30, 17, 30, 10, 30, 30,  1, 30],
       [30, 16,  5, 30, 30, 22, 30, 15, 30, 25],
       [30, 30,  0, 30, 29,  1, 19,  4, 30,  7],
       [29, 30,  1, 12,  3, 30,  7, 30, 24,  6],
       [13, 28, 30, 20, 30, 30, 30, 30, 24, 30]])

### Slicing

In [102]:
x = np.array([1,2,3])
x[1:]

array([2, 3])

In [103]:
r[1:2, 2:]

array([[30, 11,  7,  1, 30, 30, 25, 20]])

In [104]:
r[0:2,0:3]

array([[30, 15, 30],
       [ 6, 14, 30]])

In [105]:
# Numpy permite crear máscaras fácilmente usando condiciones booleanas
r>25

array([[ True, False,  True,  True,  True,  True, False,  True,  True,
        False],
       [False, False,  True, False, False, False,  True,  True, False,
        False],
       [ True, False, False, False, False,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False,  True,  True,  True,
        False],
       [False, False,  True, False, False, False, False,  True, False,
        False],
       [False,  True,  True, False,  True, False,  True,  True, False,
         True],
       [ True, False, False,  True,  True, False,  True, False,  True,
        False],
       [ True,  True, False,  True,  True, False, False, False,  True,
        False],
       [ True,  True, False, False, False,  True, False,  True, False,
        False],
       [False,  True,  True, False,  True,  True,  True,  True, False,
         True]])

In [106]:
# Extraer los valores de x que satisfacen la condición booleana. Para ello usamos la máscara
r[r>25]

array([30, 30, 27, 30, 30, 30, 26, 30, 30, 30, 30, 30, 30, 30, 27, 30, 30,
       30, 30, 30, 30, 27, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 29, 30, 29, 30, 30, 30, 28, 30, 30, 30, 30, 30, 30])

In [107]:
# Sumar los valores de un arreglo 2D a lo largo del eje Y (columnas)
np.sum(r, axis=0)

array([213, 178, 177, 181, 190, 202, 226, 259, 236, 173])

In [108]:
# Sumar los valores de un arrego 2D a lo largo del eje X (filas)
np.sum(r, axis=1)

array([240, 174, 225, 178, 151, 217, 233, 180, 172, 265])

### Copiando arrays

<br>Para evitar esto, use `r.copy` para crear una copia que no afecte la matriz original:

In [109]:
copia_r = r.copy()
copia_r

array([[30, 15, 30, 27, 30, 30,  6, 30, 26, 16],
       [ 6, 14, 30, 11,  7,  1, 30, 30, 25, 20],
       [30, 12, 18, 17,  1, 30, 30, 30, 27, 30],
       [22,  3,  3, 11, 21, 25, 30, 30, 30,  3],
       [11,  3, 30,  6,  9, 23, 14, 30, 19,  6],
       [12, 27, 30, 17, 30, 10, 30, 30,  1, 30],
       [30, 16,  5, 30, 30, 22, 30, 15, 30, 25],
       [30, 30,  0, 30, 29,  1, 19,  4, 30,  7],
       [29, 30,  1, 12,  3, 30,  7, 30, 24,  6],
       [13, 28, 30, 20, 30, 30, 30, 30, 24, 30]])

### Iterando sobre matrices

Creamos una nueva matriz de 4 por 3 con números aleatorios de 0-9:

In [110]:
test = np.random.randint(0, 1000, (4,3))
test

array([[ 77,   8, 206],
       [390,  65, 222],
       [198, 552, 887],
       [970,  76, 460]])

Iterar por fila:

In [111]:
for row in test:
    print(row)

[ 77   8 206]
[390  65 222]
[198 552 887]
[970  76 460]




Iterar por índice y por fila con **enumerate**:

In [112]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [ 77   8 206]
row 1 is [390  65 222]
row 2 is [198 552 887]
row 3 is [970  76 460]


## Filtros en Arrays

Suponga que desea tomar el valor de una matriz `X` cuando el valor correspondiente en una condición es True, y de lo contrario tome el valor de la matriz `Y`. Dentro de *Numpy* hay una función llamada **np.where** que resuelve la situación anterior.

```python
result = np.where(cond, xarr, yarr)
```

In [113]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [114]:
np.where(xarr>1.3,0,1)

array([1, 1, 1, 0, 0])